services:
  # PostgreSQL для File Storing Service
  db_file_storage:
    image: postgres:14
    container_name: db_file_storage
    restart: always
    environment:
      POSTGRES_DB: file_storage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Сервис хранения файлов (FastAPI)
  file_storage_app:
    build:
      context: ./file_storing_service
      dockerfile: Dockerfile
    image: file_storage_app:latest
    container_name: file_storage_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    volumes:
      - ./file_storing_service:/app
      - files_data:/data/files
    ports:
      - "8000:8000"
    depends_on:
      - db_file_storage
    environment:
      DATABASE_URL: postgresql://user:password@db_file_storage:5432/file_storage
      STORAGE_DIR: /data/files

  # PostgreSQL для File Analysis Service
  db_file_analysis:
    image: postgres:14
    container_name: db_file_analysis
    restart: always
    environment:
      POSTGRES_DB: file_analysis
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata_analysis:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  # Redis для Celery
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Сервис анализа файлов (FastAPI + Celery API)
  file_analysis_app:
    build:
      context: ./file_analysis_service
      dockerfile: Dockerfile
    image: file_analysis_app:latest
    container_name: file_analysis_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]
    volumes:
      - ./file_analysis_service:/app
    ports:
      - "8001:8001"
    depends_on:
      - db_file_analysis
      - file_storage_app
      - redis
    environment:
      DATABASE_URL:         postgresql://user:password@db_file_analysis:5432/file_analysis
      FILE_STORAGE_URL:     http://file_storage_app:8000
      CELERY_BROKER_URL:    redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1

    # Celery worker для File Analysis
  celery_worker:
    build:
      context: ./file_analysis_service
      dockerfile: Dockerfile
    image: file_analysis_app:latest
    container_name: file_analysis_worker
    command:
      - celery
      - -A
      - celery_app
      - worker
      - --loglevel=info
    volumes:
      - ./file_analysis_service:/app
    depends_on:
      - redis
      - db_file_analysis
      - file_storage_app
    environment:
      CELERY_BROKER_URL:    redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
      FILE_STORAGE_URL:     http://file_storage_app:8000
      DATABASE_URL:         postgresql://user:password@db_file_analysis:5432/file_analysis


volumes:
  pgdata_storage:
  pgdata_analysis:
  files_data:
  redis_data:
